apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: galaxy-controller-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
  - host: "galaxy.machearn.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: galaxy-controller-service
            port:
              number: 80
  tls:
  - hosts:
    - "galaxy.machearn.com"
    secretName: galaxy-cert
